INSERT INTO public.funcionalidade (id,nome) VALUES
	 (1,'MENU_DASHBOARD'),
	 (2,'MENU_TITULAR'),
	 (3,'MENU_DEPENDENTE'),
	 (4,'MENU_CARTEIRINHA'),
	 (5,'MENU_OCORRENCIA'),
	 (6,'MENU_PLANO'),
	 (7,'MENU_PRECO'),
	 (8,'MENU_FINANCEIRO'),
	 (9,'MENU_CALCULADORA'),
	 (10,'MENU_RELATORIO');
INSERT INTO public.funcionalidade (id,nome) VALUES
	 (11,'MENU_USUARIO'),
	 (12,'INSERIR_TITULAR'),
	 (13,'EDITAR_TITULAR'),
	 (14,'INATIVAR_TITULAR'),
	 (15,'ATIVAR_TITULAR'),
	 (16,'INSERIR_DEPENDENTE'),
	 (17,'EDITAR_DEPENDENTE'),
	 (18,'INATIVAR_DEPENDENTE'),
	 (19,'ATIVAR_DEPENDENTE'),
	 (20,'INSERIR_OCORRENCIA');
INSERT INTO public.funcionalidade (id,nome) VALUES
	 (21,'EDITAR_OCORRENCIA'),
	 (22,'INATIVAR_OCORRENCIA'),
	 (23,'ATIVAR_OCORRENCIA'),
	 (24,'INSERIR_PLANO'),
	 (25,'EDITAR_PLANO'),
	 (26,'INATIVAR_PLANO'),
	 (27,'ATIVAR_PLANO'),
	 (28,'INSERIR_PRECO'),
	 (29,'EDITAR_PRECO'),
	 (30,'INATIVAR_PRECO');
INSERT INTO public.funcionalidade (id,nome) VALUES
	 (31,'ATIVAR_PRECO'),
	 (32,'INSERIR_FINANCEIRO'),
	 (33,'EDITAR_FINANCEIRO'),
	 (34,'INATIVAR_FINANCEIRO'),
	 (35,'ATIVAR_FINANCEIRO'),
	 (36,'INSERIR_FINANCEIRO'),
	 (37,'EDITAR_FINANCEIRO'),
	 (38,'INATIVAR_FINANCEIRO'),
	 (39,'ATIVAR_FINANCEIRO'),
	 (40,'RELATORIO_ANIVERSARIANTES');
INSERT INTO public.funcionalidade (id,nome) VALUES
	 (41,'RELATORIO_ATRASADOS'),
	 (42,'RELATORIO_RECEBIDOS'),
	 (43,'RELATORIO_LOG'),
	 (44,'INSERIR_USUARIO'),
	 (45,'EDITAR_USUARIO'),
	 (46,'INATIVAR_USUARIO'),
	 (47,'ATIVAR_USUARIO'),
	 (48,'RESETAR_SENHA'),
	 (49,'MENU_PERFIL'),
	 (50,'INSERIR_PERFIL');
INSERT INTO public.funcionalidade (id,nome) VALUES
	 (51,'EDITAR_PERFIL');
